AWSTemplateFormatVersion: 2010-09-09
Resources:
  LogsWSO2Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: logs-wso2-oas
  LogsAPIsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: logs-apis-oas
